### ISSUE TITLE
Frontend - Wes

### ISSUE THREAD

**Issue by dzarrillo** [dzarrillo/Project1#3]
This is just a test

**Comment by RonNakata** [comment]
GUI / general layout of page

**Comment by RonNakata** [comment]
Jim and I have added some stuff

I need a row div w/ #planets to insert those clickable cards, but I can change the bootstrap column width and you can place/size that div wherever you want on the main page.

Clicking an image sends you to planet.html, with a query string saying which card clicked it, and I put the script to read that value in the bottom.  Jim and Don need to put their API return results on this page.

**Comment by dzarrillo** [comment]
done
