### ISSUE TITLE
NASA API - Jim

### ISSUE THREAD

**Issue by dzarrillo** [dzarrillo/Project1#5]
This is just a test

**Comment by RonNakata** [comment]
Takes in a string and returns the url for a photo.

**Comment by RonNakata** [comment]
Any request you have for us should go here.  I tagged you on the thread for input validation to maybe populate the image url for the db if a user adds something.  That leaves us with only validating the name input in some way... do we restrict it to a list of stuff in the solar system and consider that enough validation?

**Comment by dzarrillo** [comment]
been completed
