### ISSUE TITLE
User input validation on firebase - Ron

### ISSUE THREAD

**Issue by RonNakata** [dzarrillo/Project1#7]
Take the string returned by the Watson API and check it against a list of celestial bodies

**Comment by RonNakata** [comment]
I can potentially let people write to the DB and add a celestial body they want to check out via a new card prepended to the existing ones.  Would need them to enter some value.. however not sure how to validate them.  

would take a name and a photo url as input.

names, we can do against a some list of strings we will allow? 
how would we validate an image url I dunno.

**Comment by dzarrillo** [comment]
been completed
